language: cpp

compiler:
    - gcc

dist: trusty

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake clang libflann-dev

install:

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./run_tests
